IATI/js-validator-api

- services/rulesValidator.js
[Trello](https://trello.com/c/Iwp9gNEt)
Files > 50MiB are struggling to complete in the 230sec limit imposed by Azure Functions.
Found ~10sec by using direct xpath to split into activities vs. "//"﻿
> Performance improvements

- .github/workflows/develop-func-ci.yml
- .npmrc
- package-lock.json
- package.json
[Trello](https://trello.com/c/cTCodRTs)﻿
> pin npm version >7 so lockfile stays v2

- README.md
- pub-get-version/function.json
- pub-get-version/index.js
[Trello](https://trello.com/c/5IaxHhGS)﻿
> add endpoint to return app version

- .github/workflows/develop-func-deploy.yml
[Trello](https://trello.com/c/xvinz2al)﻿
> add max-old-space-size config at 3 GB to try smaller ASP

- .github/workflows/prod-func-deploy.yml
[Trello](https://trello.com/c/xvinz2al)﻿
> add --max-old-space-size configuration

- ruleset-unit-tests/strictSum/rules/recipient_country_region.json
- ruleset-unit-tests/strictSum/test-files/good_complex_decimals.xml
- ruleset-unit-tests/strictSum/test.js
- services/rulesValidator.js
[Trello](https://trello.com/c/fkaraLyg)﻿
> handle decimal addition better

- .github/workflows/develop-func-ci.yml
- .github/workflows/develop-func-deploy.yml
- package-lock.json
- package.json
- Fixes Issue where summation rules were failing due to rounding errors
> Next Release

- package-lock.json
- package.json
[Trello](https://trello.com/c/Wl3MWcyJ)﻿
> fix stdin 500 error with xmllint for file with weird chars

- utils/utils.js
[Trello](https://trello.com/c/OWpx8CK1)﻿
> update ruleset branch to version-2.0X pattern

- .github/workflows/develop-func-deploy.yml
[Trello](https://trello.com/c/KaQzR98d)﻿
> switch from keyvault name to URI

- .github/workflows/develop-func-deploy.yml
This reverts commit d5aa9dd7458d52cdd8f384790b260cb8ec24d104.
> Revert "switch from keyvault name to URI"

- .github/dependabot.yml
- .github/workflows/develop-func-deploy.yml
- .github/workflows/prod-func-deploy.yml
- Dockerfile
[Trello](https://trello.com/c/KaQzR98d)﻿
> upgrade to v4 Functions runtime, change to keyvault URI

- README.md
- integration-tests/js-validator-api-tests.postman_collection.json
- pvt-validate-schema-post/function.json
- pvt-validate-schema-post/index.js
- services/schemaValidator.js
[Trello](https://trello.com/c/vM4Wjqe2)
- add activity level schema validation endpoint
- add documentation for new schema-validate route
- add iati-activities check
> Single Activity Schema Validation Endpoint

- .github/workflows/develop-func-deploy.yml
- .github/workflows/prod-func-deploy.yml
[Trello](https://trello.com/c/C7ND3XM0)
[Wiki](https://github.com/IATI/IATI-Internal-Wiki/blob/main/Technical-Climate-Impact/Measurement.md)
> add tags on deploy for tech climate impact tracking

- integration-tests/js-validator-api-tests.postman_collection.json
- ruleset-unit-tests/dateNow/test.js
- services/rulesValidator.js
[Trello](https://trello.com/c/LcKfGdbX)
> handle incorrect date formats better for dateNow rule

- README.md
- integration-tests/js-validator-api-tests.postman_collection.json
- pvt-schema-validate-file-post/function.json
- pvt-schema-validate-file-post/index.js
- services/schemaValidator.js
[Trello](https://trello.com/c/C6gJkJrS)
> add schema validate file endpoint for file pre-checks before full validation

- .github/workflows/develop-func-ci.yml
- .github/workflows/develop-func-deploy.yml
- .github/workflows/prod-func-deploy.yml
- .nvmrc
- Dockerfile
- README.md
- docker-compose.yml
- package-lock.json
- package.json
[Trello](https://trello.com/c/e70ofnmE)
> upgrade to Node v16

- services/rulesValidator.js
[Trello](https://trello.com/c/Q04XIUIG)
> use xmldom to get subelements to loop over instead of xpath for speed

- README.md
- package-lock.json
- package.json
- services/schemaValidator.js
- services/validationService.js
- utils/utils.js
- utils/validate-xmllint-installation.js
[Trello](https://trello.com/c/qhAUGABD)
> bring validate-with-xmllint functionality into our codebase to remove customised dependency

- integration-tests/js-validator-api-tests.postman_collection.json
- ruleset-unit-tests/dupIdentifier/test.js
- ruleset-unit-tests/identifier/test.js
- services/rulesValidator.js
- services/validationService.js
- utils/utils.js
[Trello](https://trello.com/c/Q04XIUIG)
- split stream transform working, linenumber still broken
- fix error message
- fix schema validation to use string from streaming
- fix line numbers for schema and ruleset errors after streaming
> Use Streams to Improve Validation Speed

- integration-tests/js-validator-api-tests.postman_collection.json
- integration-tests/test-files/iati-multi-act-atLeastOne-error.xml
- integration-tests/test-files/iati-multi-act-dateNow-error.xml
- integration-tests/test-files/iati-multi-act-dateOrder-error.xml
- integration-tests/test-files/iati-multi-act-noMoreThanOne-error.xml
- integration-tests/test-files/iati-multi-act-noSpaces-error.xml
- integration-tests/test-files/iati-multi-act-oneOrAll-error.xml
- integration-tests/test-files/iati-multi-act-range-ifThen-error.xml
- integration-tests/test-files/iati-multi-act-regexMatches-error.xml
- integration-tests/test-files/iati-multi-act-strictSum-error.xml
- integration-tests/test-files/iati-multi-act-timeLimit-error.xml
- integration-tests/test-files/iati-multi-org-betweenDates-error.xml
- integration-tests/test-files/iati-multi-unique-startsWith-error.xml
- services/rulesValidator.js
[Trello](https://trello.com/c/Q04XIUIG)
- make line numbers work for all rule test cases and add tests
> Fix line numbers and add tests for them

- utils/utils.js
[Trello](https://trello.com/c/iiM4FkDh)
> fix redis command after es modules migration

- README.md
- utils/utils.js
[Trello](https://trello.com/c/tYdinKiA)
> use IATI-Validator-Codelists as source for codelist rules

- README.md
- utils/utils.js
[Trello](https://trello.com/c/tYdinKiA)
> use IATI-Validator-Codelists for codelist repo

- README.md
- services/validationService.js
- utils/utils.js
[Trello](https://trello.com/c/Wn3u6UPh)
> update caching method to always check for a new file using content-disposition header

- config/redis.js
- package-lock.json
- package.json
[Trello](https://trello.com/c/wrMSFSFa)
> upgrade redis and implement exponential backoff reconnect strategy

- Dockerfile
[Trello](https://trello.com/c/DaIUQtsb)
> replace deprecated set-script command in npm build process

- README.md
- package-lock.json
- package.json
[Trello](https://trello.com/c/EWUY1xXH)
> update forked xpath dependency to use a release tag

- integration-tests/js-validator-api-tests.postman_collection.json
- integration-tests/test-files/iati-multi-act-self-closed.xml
- services/rulesValidator.js
[Trello](https://trello.com/c/x6F9VNpH)
> handle self-closed iati-activity elements appropriately

- utils/utils.js
https://trello.com/c/JxeUDUPp/346-investigate-huge-input-lookup-error
> Parse XML with huge_tree enabled for deep elements

- services/rulesValidator.js
[Ticket ](https://trello.com/c/LO7Z9ReH/344-improve-description-narrative-error-messages-and-guidance)
> Feature | Improve Description Error Message
